"""
make_icon.py  -  draws the PACMANGRAM icon: a Pacman painted in the Instagram gradient.

Outputs (next to the project):
  assets/app.ico          multi-size Windows icon (used for the .exe)
  assets/app_preview.png  1024 px preview
  src/igdm_assets.py      the same icon embedded as base64 (so the exe needs no data files)

Everything is drawn from scratch with Pillow (supersampled for smooth edges).
"""

import base64
import io
import math
import os

from PIL import Image, ImageDraw, ImageChops

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
S = 1024            # master canvas
SS = 2              # supersampling factor for anti-aliasing

# Instagram-style gradient: yellow > orange > pink > purple > blue
IG_STOPS = [(0.0, (254, 218, 117)), (0.28, (250, 126, 30)), (0.52, (214, 41, 118)), (0.76, (150, 47, 191)),
            (1.0, (79, 91, 213))]


def ig_gradient(size):
    """Starts bottom-left (yellow) and sweeps to the top-right (blue), like the Instagram logo."""
    img = Image.new("RGB", (size, size))
    px = img.load()
    span = math.hypot(size, size) * 0.98
    ox, oy = size * 0.12, size * 0.98
    for y in range(size):
        for x in range(size):
            t = min(1.0, math.hypot(x - ox, y - oy) / span)
            for (t0, c0), (t1, c1) in zip(IG_STOPS, IG_STOPS[1:]):
                if t0 <= t <= t1:
                    k = (t - t0) / (t1 - t0)
                    px[x, y] = tuple(int(c0[i] + (c1[i] - c0[i]) * k) for i in range(3))
                    break
    return img


def draw_master():
    """A Pacman in the Instagram gradient; its eye is a white camera-lens ring; two pellets follow the mouth."""
    n = S * SS
    k = SS
    cx, cy, r = 400 * k, 512 * k, 380 * k            # body
    half = math.radians(37)                          # half mouth opening (mouth points to the right)

    body = Image.new("L", (n, n), 0)
    ImageDraw.Draw(body).ellipse((cx - r, cy - r, cx + r, cy + r), fill=255)
    far = r * 3
    wedge = Image.new("L", (n, n), 255)
    ImageDraw.Draw(wedge).polygon(
        [(cx, cy), (cx + far * math.cos(-half), cy + far * math.sin(-half)),
         (cx + far * math.cos(half), cy + far * math.sin(half))], fill=0)
    mask = ImageChops.multiply(body, wedge)

    grad = ig_gradient(2 * r).convert("RGBA")
    pac = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    pac.paste(grad, (cx - r, cy - r))
    pac.putalpha(mask)

    d = ImageDraw.Draw(pac)
    # eye = Instagram lens: white ring with a centre dot
    ex, ey = cx + 40 * k, cy - 195 * k
    ro, ri = 62 * k, 38 * k
    d.ellipse((ex - ro, ey - ro, ex + ro, ey + ro), fill=(255, 255, 255, 255))
    d.ellipse((ex - ri, ey - ri, ex + ri, ey + ri), fill=(150, 47, 191, 255))
    d.ellipse((ex - 17 * k, ey - 17 * k, ex + 17 * k, ey + 17 * k), fill=(255, 255, 255, 255))

    # pellets in the gradient colours, following the mouth
    for px_, col in ((815, (250, 126, 30)), (925, (214, 41, 118))):
        pr = 34 * k
        d.ellipse((px_ * k - pr, cy - pr, px_ * k + pr, cy + pr), fill=col + (255,))

    art = pac.resize((S, S), Image.LANCZOS)
    art = art.crop(art.getbbox())
    scale = (S * 0.90) / max(art.size)
    art = art.resize((max(1, int(art.width * scale)), max(1, int(art.height * scale))), Image.LANCZOS)
    out = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    out.alpha_composite(art, ((S - art.width) // 2, (S - art.height) // 2))
    return out


def main():
    master = draw_master()
    assets = os.path.join(ROOT, "assets")
    os.makedirs(assets, exist_ok=True)
    master.save(os.path.join(assets, "app_preview.png"))
    sizes = [16, 24, 32, 48, 64, 128, 256]
    master.save(os.path.join(assets, "app.ico"), format="ICO", sizes=[(s, s) for s in sizes])

    small = master.resize((44, 44), Image.LANCZOS)   # sidebar logo
    buf = io.BytesIO()
    small.save(buf, format="PNG", optimize=True)
    png_b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    big = master.resize((150, 150), Image.LANCZOS)      # intro screen logo
    buf2 = io.BytesIO()
    big.save(buf2, format="PNG", optimize=True)
    png_large_b64 = base64.b64encode(buf2.getvalue()).decode("ascii")
    with open(os.path.join(assets, "app.ico"), "rb") as fp:
        ico_b64 = base64.b64encode(fp.read()).decode("ascii")

    def wrap(s, w=100):
        return "\n".join(f'    "{s[i:i + w]}"' for i in range(0, len(s), w))

    with open(os.path.join(ROOT, "src", "igdm_assets.py"), "w", encoding="utf-8") as fp:
        fp.write('"""Generated by tools/make_icon.py - the app icon embedded as base64."""\n\n')
        fp.write(f"ICON_PNG_B64 = (\n{wrap(png_b64)}\n)\n\n")
        fp.write(f"ICON_PNG_LARGE_B64 = (\n{wrap(png_large_b64)}\n)\n\n")
        fp.write(f"ICON_ICO_B64 = (\n{wrap(ico_b64)}\n)\n")
    print("icon written:", os.path.join(assets, "app.ico"))


if __name__ == "__main__":
    main()
