"""English catalog. Keys are the Turkish source strings used in the code; every {n} placeholder must stay."""

CATALOG = {
    "Henüz sohbet seçilmedi.\nSağ üstteki 'Sohbet seç' düğmesiyle bir sohbet seç.":
        "No chat selected yet.\nPick one with the 'Select chat' button at the top right.",
    "mesaj": "message",
    "sohbet": "chat",
    "story": "story",
    "kişi": "account",
    "beğeni": "like",
    "kayıt": "saved item",
    "dosya": "file",
    "Hız: {0} · her {1} arasında {2}–{3} sn": "Speed: {0} · {2}–{3} s between each {1}",
    "Geri çekilen: {0} · başarısız: {1}": "Unsent: {0} · failed: {1}",
    "Program açıldı. Ağ kilidi aktif: yalnızca Instagram/Facebook sunucularına bağlanılır.":
        "App started. Network lock active: it only connects to Instagram/Facebook servers.",
    "Dil değiştirildi: {0}": "Language changed: {0}",
    "HESAP": "ACCOUNT",
    "DM ARAÇLARI": "DM TOOLS",
    "TEMİZLİK ARAÇLARI": "CLEANUP TOOLS",
    "Çıkış yap ve oturumu sil": "Log out and delete session",
    "Şifreyle giriş yap": "Log in with password",
    "Oturumla giriş yap": "Log in with session",
    "Yenile": "Refresh",
    "Sohbetler burada listelenir.": "Chats are listed here.",
    "Bu sohbeti seç  →": "Select this chat  →",
    "Daha fazla yükle": "Load more",
    "Sohbeti komple sil": "Delete entire chat",
    "Sohbet seç  →": "Select chat  →",
    "Yükle / Ara": "Load / Search",
    "Benim mesajlarımı seç": "Select my messages",
    "Durdur": "Stop",
    "Seçili mesajlarımı geri çek": "Unsend selected messages",
    "Hız profili: {0}": "Speed profile: {0}",
    "Beklenmeyen hata: {0}": "Unexpected error: {0}",
    "Durdurma isteği alındı...": "Stop requested...",
    "{0} için giriş deneniyor...": "Trying to log in as {0}...",
    "Tarayıcı oturumuyla giriş deneniyor...": "Trying to log in with the browser session...",
    "Giriş başarılı: @{0}": "Logged in: @{0}",
    "Sohbetler yükleniyor...": "Loading chats...",
    "Bilinmeyen": "Unknown",
    "Sohbet seçildi: {0}": "Chat selected: {0}",
    " Daha eski mesajlar da var: 'En çok kaç mesaj' değerini artırıp tekrar yükle.":
        " There are older messages too: raise 'Max messages' and load again.",
    "Yükleme bitti: {0} mesaj, senin: {1}, listelenen: {2}.{3}":
        "Loading done: {0} messages, yours: {1}, listed: {2}.{3}",
    "\n\n({0} seçili satır karşı tarafın olduğu için atlanacak.)":
        "\n\n({0} selected rows belong to the other person and will be skipped.)",
    "\n\nSohbet silinemedi (ayrıntı günlükte).": "\n\nThe chat could not be deleted (details in the log).",
    "\n\nİşlem durduruldu; kalanlar listede duruyor.": "\n\nStopped; the remaining ones are still in the list.",
    "Sohbetleri tara ve planla": "Scan chats and plan",
    "Otomatik temizliği başlat": "Start automatic cleanup",
    "Koru / korumayı kaldır": "Protect / unprotect",
    "Sohbetleri taramak için yukarıdaki düğmeye bas.\nSonra silinecekleri görürsün.":
        "Press the button above to scan your chats.\nThen you will see which ones will be deleted.",
    "Otomatik temizlik: tüm sohbetler taranıyor...": "Automatic cleanup: scanning all chats...",
    "{0} sohbet bulundu.": "{0} chats found.",
    "\n\nKendi mesajların da geri çekileceği için bu ÇOK daha uzun sürer (saatler / günler).":
        "\n\nBecause your own messages are unsent too, this takes MUCH longer (hours / days).",
    "Onay gerekli": "Confirmation required",
    "{0} sohbet komple silinecek, {1} sohbet korunacak.\nTahmini süre (yalnızca silme): yaklaşık {2} ({3} hız).{4}\n\nBu işlem geri alınamaz. Silinen sohbetler gelen kutundan kalkar (karşı taraf kendi tarafında görmeye devam eder).\nİşlem sürerken bilgisayar uykuya geçmez; pencereyi açık bırak. Instagram uyarı verirse program kendiliğinden yavaşlar ya da durur.\n\nOnaylamak için  {5}  yaz:":
        "{0} chats will be deleted completely, {1} chats will be kept.\nEstimated time (deletion only): about {2} ({3} speed).{4}\n\nThis cannot be undone. Deleted chats disappear from your inbox (the other person still sees them on their side).\nYour computer will not go to sleep while this runs; keep the window open. If Instagram warns, the app slows down or stops by itself.\n\nType  {5}  to confirm:",
    "Otomatik temizlik başladı ({0} hız): {1} sohbet silinecek.":
        "Automatic cleanup started ({0} speed): {1} chats will be deleted.",
    "Silinen sohbet: {0} · başarısız: {1}": "Deleted chats: {0} · failed: {1}",
    "\n\nInstagram sınırlama uyardığı için durduruldu. Birkaç saat sonra tekrar başlatabilirsin.":
        "\n\nStopped because Instagram issued a rate-limit warning. You can start again in a few hours.",
    "Bir işlem sürerken dil değiştirilemez. Önce işlemi durdur.":
        "The language cannot be changed while a task is running. Stop the task first.",
    "Giriş yapılmadı": "Not logged in",
    "Bağlı değil": "Not connected",
    "▾  Etkinlik günlüğü": "▾  Activity log",
    "Günlük dosyasını aç": "Open log file",
    "Temizle": "Clear",
    "Kişiler": "People",
    "Son mesaj": "Last message",
    "Sohbet: seçilmedi": "Chat: none selected",
    "Tarih": "Date",
    "Gönderen": "Sender",
    "Mesaj": "Message",
    "Şifre değişikliği iptal edildi.": "Password change cancelled.",
    "Kayıtlı oturum aranıyor...": "Looking for a saved session...",
    "Kullanıcı adı ve şifreyi yaz.": "Enter the username and password.",
    "Giriş yapılıyor...": "Logging in...",
    "Bu geçerli bir 'sessionid' değerine benzemiyor.\nDeğer uzun bir metindir ve bir sayıyla başlar (örn. 1234567890%3Aabc...).":
        "This does not look like a valid 'sessionid'.\nIt is a long text that starts with a number (e.g. 1234567890%3Aabc...).",
    "Tarayıcı oturumuyla giriş yapılıyor...": "Logging in with the browser session...",
    "Önce süren işlemi durdur.": "Stop the running task first.",
    "Çıkış yapıldı.": "Logged out.",
    "Başka sohbet yok.": "No more chats.",
    "Listeden bir sohbet seç.": "Pick a chat from the list.",
    "Sohbet: {0}": "Chat: {0}",
    "Önce 'Sohbet seç' sayfasından (ya da sağ üstteki düğmeyle) bir sohbet seç.":
        "First pick a chat on the 'Select chat' page (or with the button at the top right).",
    "Bu sohbette (bu aramayla) mesaj bulunamadı.": "No messages found in this chat (with this search).",
    "Mesajlar yükleniyor...": "Loading messages...",
    "Ben": "Me",
    "Yüklenen mesaj: {0} · senin: {1}": "Loaded messages: {0} · yours: {1}",
    "{0} mesaj yüklendi, {1} tanesi senin.{2}": "{0} messages loaded, {1} of them yours.{2}",
    "{0} seçili · {1} benim · {2} listelenen": "{0} selected · {1} mine · {2} listed",
    "Geri çekilecek kendi mesajın seçili değil.\n(Karşı tarafın mesajları geri çekilemez.)":
        "None of your own messages are selected.\n(The other person's messages cannot be unsent.)",
    "{0} mesajın geri çekilecek (herkes için silinir, geri alınamaz).\n\n{1}. Ara sıra kısa dinlenme molaları verilir; Instagram uyarı verirse program kendiliğinden yavaşlar ya da durur.\nTahmini süre: yaklaşık {2}. Bu sürede bilgisayar uykuya geçmez, pencereyi açık bırak.{3}\n\nDevam edilsin mi?":
        "{0} of your messages will be unsent (deleted for everyone, cannot be undone).\n\n{1}. Short rests are taken now and then; if Instagram warns, the app slows down or stops by itself.\nEstimated time: about {2}. Your computer will not go to sleep meanwhile; keep the window open.{3}\n\nContinue?",
    "Silmeden önce yüklenen {0} mesajımı da geri çek (karşı taraftan da kaybolur; yavaş: yaklaşık {1})":
        "Also unsend my {0} loaded messages before deleting (they vanish for the other person too; slow: about {1})",
    "Sohbet silindi: {0}": "Chat deleted: {0}",
    "İşlem bitti. {0}.": "Finished. {0}.",
    "\n\nİşlem tamamlanmadığı için sohbet silinmedi.": "\n\nThe chat was not deleted because the task did not complete.",
    "Önce 'Sohbetleri tara ve planla' düğmesine bas.": "Press 'Scan chats and plan' first.",
    "Durum": "Status",
    "Son etkinlik": "Last activity",
    "Koruma kaldırıldı: {0}": "Protection removed: {0}",
    "Korumaya alındı: {0}": "Protected: {0}",
    "Tüm sohbetler taranıyor...": "Scanning all chats...",
    "{0} korunacak ({1} elle korumalı) · {2} silinecek": "{0} kept ({1} protected by hand) · {2} to delete",
    "SİL": "DELETE",
    "Otomatik temizlik onaylanmadı, iptal edildi.": "Automatic cleanup was not confirmed and was cancelled.",
    " · kalan: {0}": " · remaining: {0}",
    "Otomatik temizlik bitti. {0}.": "Automatic cleanup finished. {0}.",
    "\n\nİşlem tamamlanmadı. 'Sohbetleri tara ve planla' ile yeniden tarayıp devam edebilirsin.":
        "\n\nThe task did not complete. You can rescan with 'Scan chats and plan' and continue.",
    "Giriş": "Login",
    "Hesap bilgisi": "Account info",
    "Sohbet seç": "Select chat",
    "Mesajlar": "Messages",
    "DM temizlik": "DM cleanup",
    "Sohbet yedekle": "Chat backup",
    "Story arşivi": "Story archive",
    "Engeller": "Blocks",
    "Beğeniler": "Likes",
    "Kaydedilenler": "Saved",
    "● Bağlı": "● Connected",
    "▸  Etkinlik günlüğü": "▸  Activity log",
    "Günlük dosyası henüz oluşmadı.": "The log file has not been created yet.",
    "Günlük dosyası açılamadı: {0}": "Could not open the log file: {0}",
    "işlem": "action",
    "Bir işlem sürüyor. Yine de kapatılsın mı?": "A task is running. Close anyway?",
    "Instagram doğrulama kodu istiyor ({0}).\nGelen kodu yaz:": "Instagram is asking for a verification code ({0}).\nEnter the code you received:",
    "Instagram yeni bir şifre belirlemeni istiyor.\nYeni şifreyi yaz:": "Instagram wants you to set a new password.\nEnter the new password:",
    " Kayıtlı oturum silindi.": " Saved session deleted.",
    "Mesajlar yükleniyor": "Loading messages",
    "Vazgeç": "Cancel",
    "Sohbeti sil": "Delete chat",
    "Sohbet silindi.": "Chat deleted.",
    "Sohbet silindi.\n\n{0}": "Chat deleted.\n\n{0}",
    "Bitti · {0}": "Done · {0}",
    " Kullanıcı durdurdu.": " Stopped by the user.",
    "Tarama durduruldu.": "Scan stopped.",
    "Korumalı ★": "Protected ★",
    "Önce listeden bir kayıt seç (ya da çift tıkla).": "Pick an entry from the list first (or double-click).",
    "{0}/{1} · {2} işleniyor...": "{0}/{1} · processing {2}...",
    "Şu tarihten önce (GG.AA.YYYY):": "Before this date (DD.MM.YYYY):",
    " önce": " ago",
    "(GG.AA.YYYY)": "(DD.MM.YYYY)",
    "{0}: story {1}/{2} işlendi · sonraki {3} sn sonra{4}": "{0}: story {1}/{2} done · next in {3} s{4}",
    "Gönderi": "Post",
    "{0}: tarama hatası: {1}": "{0}: scan error: {1}",
    "{0}/{1} işlendi · sonraki {2} sn sonra{3} · kalan ≈ {4}": "{0}/{1} done · next in {2} s{3} · remaining ≈ {4}",
    "{0:.1f} saat": "{0:.1f} h",
    "Güvenli": "Safe",
    "Dengeli": "Balanced",
    "Hızlı": "Fast",
    "{0} sn": "{0} s",
    "{0:.0f} dk": "{0:.0f} min",
    "Güvenlik kilidi bağlantıyı engelledi: {0}": "The security lock blocked a connection: {0}",
    "Instagram bu programın kullandığı uygulama sürümünü artık kabul etmiyor (şifreyle girişte bilinen sorun, özellikle 2 adımlı doğrulamalı hesaplarda). Şifre veya kodun yanlış değil. Sağdaki 'B · Tarayıcı oturumuyla giriş' yöntemini dene.":
        "Instagram no longer accepts the app version this program uses (a known issue with password login, especially for accounts with two-step verification). Your password or code is not wrong. Try method 'B · Log in with browser session' on the right.",
    "Kullanıcı adı veya şifre hatalı.": "Wrong username or password.",
    "Instagram ek doğrulama istiyor. Instagram uygulamasında 'Bu bendim' bildirimini onayla, sonra tekrar dene.":
        "Instagram wants extra verification. Approve the 'This was me' prompt in the Instagram app, then try again.",
    "Instagram oturumun süresi dolmuş. Çıkış yapıp tekrar giriş yap.": "Your Instagram session has expired. Log out and log in again.",
    "Instagram hesabı geçici olarak sınırladı / uyardı. Birkaç saat bekleyip tekrar dene.":
        "Instagram temporarily limited / warned the account. Wait a few hours and try again.",
    "Bağlantı sorunu: internet bağlantını kontrol et (işlem bağlantı gelince kendiliğinden yeniden denenir).":
        "Connection problem: check your internet connection (the task retries by itself once you are back online).",
    "Yedekler": "Backups",
    "Sesli mesaj": "Voice message",
    "   (tepkiler: {0})": "   (reactions: {0})",
    "{0}\n\nKlasör:\n{1}": "{0}\n\nFolder:\n{1}",
    "Klasör seç…": "Choose folder…",
    "Klasörü aç": "Open folder",
    "Sohbetleri yükle": "Load chats",
    "Seçilenleri yedekle": "Back up selected",
    "Hepsini seç": "Select all",
    "Henüz sohbet yüklenmedi.\nYukarıdaki düğmeyle sohbetlerini listele.":
        "No chats loaded yet.\nUse the button above to list your chats.",
    "Sohbet yedekle: {0} sohbet listelendi.": "Chat backup: {0} chats listed.",
    "Sohbet yedekle: {0} sohbet yedeklenecek → {1}": "Chat backup: {0} chats will be backed up → {1}",
    "klasör adı çakışması": "folder name clash",
    "gorseller": "images",
    "videolar": "videos",
    "sesli_mesajlar": "voice_messages",
    "PACMANGRAM · Sohbet yedeği": "PACMANGRAM · Chat backup",
    "Sohbet     : {0}": "Chat        : {0}",
    "Katılımcı  : {0}": "Participants: {0}",
    "Yedek tarihi: {0:%Y-%m-%d %H:%M:%S}": "Backup date : {0:%Y-%m-%d %H:%M:%S}",
    "Mesaj sayısı: {0}": "Messages    : {0}",
    "sohbet.txt": "chat.txt",
    "Yedeklenen sohbet: {0} · mesaj: {1} · dosya: {2}": "Backed-up chats: {0} · messages: {1} · files: {2}",
    "\n\nInstagram sınırlama uyardığı için durduruldu. Birkaç saat sonra kalan sohbetleri yedekleyebilirsin.":
        "\n\nStopped because Instagram issued a rate-limit warning. You can back up the remaining chats in a few hours.",
    "Ad soyad": "Full name",
    "Kullanıcı ID": "User ID",
    "Hesap açılış tarihi": "Account created",
    "Hesap yaşı": "Account age",
    "Ülke": "Country",
    "Eski kullanıcı adları": "Former usernames",
    "Gönderi sayısı": "Posts",
    "Takipçi": "Followers",
    "Takip edilen": "Following",
    "Hesap türü": "Account type",
    "Biyografi": "Biography",
    "Web sitesi": "Website",
    "E-posta (gizli)": "Email (masked)",
    "Telefon (gizli)": "Phone (masked)",
    "Önce 'Sohbetleri yükle' düğmesine bas.": "Press 'Load chats' first.",
    "Sohbet": "Chat",
    "Yedek klasörünü seç": "Choose the backup folder",
    "{0} seçili · {1} sohbet": "{0} selected · {1} chats",
    "Önce yedeklenecek sohbetleri seç.\n(Ctrl / Shift ile çoklu seçim yapabilir ya da 'Hepsini seç' düğmesini kullanabilirsin.)":
        "Select the chats to back up first.\n(Use Ctrl / Shift for multi-select or the 'Select all' button.)",
    " · hata: {0}": " · errors: {0}",
    "Sohbet yedekle: bitti. {0}.": "Chat backup: finished. {0}.",
    "Hesap bilgileri okunuyor...": "Reading account info...",
    "Doğrulanmış ✓": "Verified ✓",
    "İşletme hesabı": "Business account",
    "1 aydan az": "Less than 1 month",
    "Hesap bilgisi güncellendi.": "Account info updated.",
    "Klasör açılamadı: {0}": "Could not open the folder: {0}",
    "{0} sohbet yüklendi. Yedeklemek istediklerini seç.": "{0} chats loaded. Select the ones you want to back up.",
    "Sohbet bulunamadı.": "No chats found.",
    "Yedek klasörü oluşturulamadı:\n{0}\n\n{1}": "Could not create the backup folder:\n{0}\n\n{1}",
    "ben": "me",
    "Gizli hesap": "Private account",
    "Herkese açık hesap": "Public account",
    "{0} ay": "{0} mo",
    "Bilgiler güncel.": "Info is up to date.",
    " ({0} uyarı)": " ({0} warnings)",
    "[Sistem] {0}": "[System] {0}",
    "Sohbetleri yedekle (TXT + görseller)": "Back up chats (TXT + images)",
    "Seçtiğin sohbetleri tek tek dışa aktarır. Her kişi için kendi adında bir klasör açılır: içinde sohbetin metin dosyası (sohbet.txt) ve sohbette gönderilen görseller olur. Bu işlem yalnızca OKUR; hiçbir şey silinmez.":
        "Exports the chats you select one by one. A folder named after each person is created, containing the chat as a text file (chat.txt) and the images sent in the chat. This only READS; nothing is deleted.",
    "Yedek klasörü:": "Backup folder:",
    "Görselleri indir": "Download images",
    "Videoları indir (büyük olabilir)": "Download videos (can be large)",
    "Sesli mesajları indir": "Download voice messages",
    "Bekliyor": "Waiting",
    "Tamam ✓  ({0} mesaj, {1} dosya, {2} indirilemedi)": "Done ✓  ({0} messages, {1} files, {2} failed)",
    "Tamam ✓  ({0} mesaj, {1} dosya)": "Done ✓  ({0} messages, {1} files)",
    "Hesap açılış tarihi Instagram'ın 'Bu hesap hakkında' bilgisinden okunur; Instagram bunu bazı hesaplarda vermeyebilir. E-posta ve telefon ekranda kısmen gizlenir.":
        "The account creation date is read from Instagram's 'About this account' info; Instagram may not provide it for some accounts. Email and phone are partly masked on screen.",
    "Hesap bilgisi okunamadı: {0}": "Could not read account info: {0}",
    "Profil sayıları okunamadı: {0}": "Could not read profile counts: {0}",
    "Hesap açılış tarihi Instagram'dan alınamadı (Ayarlar → Hesap merkezi → Bilgilerini indir bölümünde bulunur).":
        "The account creation date could not be retrieved from Instagram (it is found under Settings → Accounts Center → Download your information).",
    "{0} yıl ": "{0} yr ",
    "{0}: {1} mesaj okundu...": "{0}: {1} messages read...",
    "Yedekleniyor…": "Backing up…",
    "Yedeklendi: {0} → {1} mesaj, {2} dosya ({3})": "Backed up: {0} → {1} messages, {2} files ({3})",
    "{0}: dosya {1} indiriliyor...": "{0}: downloading file {1}...",
    "Yüklenen sohbet: {0}": "Loaded chats: {0}",
    "Sohbet yedekle: yüklenemedi: {0}": "Chat backup: could not load: {0}",
    "Dosya indirilemedi ({0}): {1}": "Could not download file ({0}): {1}",
    "Durduruldu.": "Stopped.",
    "Sohbetler yüklenemedi: {0}": "Could not load chats: {0}",
    "Durduruldu": "Stopped",
    "Instagram sınırlama uyardı. Hesabı korumak için DURDURULDU. Birkaç saat sonra tekrar dene.":
        "Instagram issued a rate-limit warning. STOPPED to protect the account. Try again in a few hours.",
    "v{0}  ·  Instagram için Pacman'li temizlik aracı": "v{0}  ·  Instagram toolkit with a Pacman",
    "Ücretsiz  ·  Tüm hakları saklıdır": "Free  ·  All rights reserved",
    "Hesabını hafiflet. Pacman yesin.": "Lighten your account. Let Pacman eat.",
    "Made by": "Made by",
    "Atlamak için tıkla ya da bir tuşa bas": "Click or press any key to skip",
    "Geç  ›": "Skip  ›",
    "[Fotoğraf/Video]": "[Photo/Video]",
    "[Geçici medya]": "[Disappearing media]",
    "[Sesli mesaj]": "[Voice message]",
    "[Beğeni]": "[Like]",
    "[Bağlantı]": "[Link]",
    "[Reel paylaşımı]": "[Reel share]",
    "[Gönderi paylaşımı]": "[Post share]",
    "[Klip]": "[Clip]",
    "[GIF]": "[GIF]",
    "[Hikaye paylaşımı]": "[Story share]",
    "[Video paylaşımı]": "[Video share]",
    "[Sistem mesajı]": "[System message]",
    "[Paylaşım]": "[Share]",
    "[{0}]": "[{0}]",
    "diğer": "other",
    "Program zaten açık. Aynı anda iki kopya çalıştırılamaz (istek hızı ikiye katlanır ve Instagram uyarısı riski artar).":
        "The app is already running. Two copies cannot run at once (the request rate would double and the risk of an Instagram warning rises).",
    "Program başlatılamadı:\n\n{0}\n\nAyrıntı:\n{1}": "The app could not start:\n\n{0}\n\nDetails:\n{1}",
    "Hayır": "No",
    "Evet, devam et": "Yes, continue",
}

CATALOG.update({
    "Tahmini süre: yaklaşık {0} · {1}": "Estimated time: about {0} · {1}",
    "HIZ PROFİLİ": "SPEED PROFILE",
    "DİL": "LANGUAGE",
    "Uyarıda uzun mola verip kendiliğinden devam et": "Take a long rest on a warning and resume by itself",
    "A · Şifreyle giriş": "A · Password login",
    "2 adımlı doğrulaman varsa kod soracağım.": "If you use two-step verification I will ask for the code.",
    "Kullanıcı adı": "Username",
    "Şifre": "Password",
    "Gizle": "Hide",
    "B · Tarayıcı oturumuyla giriş": "B · Browser session login",
    "Şifreyle giriş 'sürüm eski' hatası verirse bunu kullan.": "Use this if password login fails with an 'out of date' error.",
    "1) Tarayıcıda instagram.com'a giriş yap.\n2) F12 → Application (Uygulama) → Cookies → instagram.com\n3) 'sessionid' değerini kopyalayıp aşağı yapıştır.":
        "1) Log in to instagram.com in your browser.\n2) F12 → Application → Cookies → instagram.com\n3) Copy the 'sessionid' value and paste it below.",
    "Bu değer şifre gibidir, kimseyle paylaşma.": "This value works like a password; never share it.",
    "Bu bilgisayarda oturumu şifreli hatırla (bir sonraki açılışta tekrar giriş gerekmesin)":
        "Remember the session encrypted on this computer (no login needed next time)",
    "Gizlilik: şifren diske yazılmaz. Program yalnızca Instagram sunucularına bağlanır (başka adresler engellenir). Oturumu hatırlarsan yalnızca bu Windows hesabının açabileceği şekilde şifrelenir.":
        "Privacy: your password is never written to disk. The app only connects to Instagram servers (other addresses are blocked). If you remember the session it is encrypted so only this Windows account can open it.",
    "Mesajlarını temizlemek istediğin sohbeti seç": "Pick the chat whose messages you want to clean up",
    "Ara:": "Search:",
    "(kullanıcı adı veya mesaj metni)": "(username or message text)",
    "Kelime(ler):": "Word(s):",
    "En çok kaç mesaj:": "Max messages:",
    "Sohbeti seçince mesajlar otomatik yüklenir. Gri satırlar karşı tarafındır ve geri çekilemez. Kendi mesajlarını seçip geri çekebilir ya da 'Sohbeti komple sil' ile tüm sohbeti gelen kutundan kaldırabilirsin. Kelime yazarsan yalnızca eşleşenler listelenir.":
        "Messages load automatically when you pick a chat. Grey rows belong to the other person and cannot be unsent. You can select and unsend your own messages, or remove the whole chat from your inbox with 'Delete entire chat'. If you type a word only matching messages are listed.",
    "{0} sohbet listelendi.": "{0} chats listed.",
    " (kelime: {0})": " (word: {0})",
    "“{0}” sohbeti silinecek": "The chat “{0}” will be deleted",
    "Sohbet, Instagram'daki 'Sil' seçeneği gibi gelen kutundan kaldırılır. Bu yalnızca SENİN hesabındaki sohbeti siler; karşı tarafın mesajları ve senin gönderdiklerin onda kalmaya devam eder. Geri alınamaz.":
        "The chat is removed from your inbox like Instagram's 'Delete' option. This only deletes the chat on YOUR account; the other person keeps the messages, including the ones you sent. It cannot be undone.",
    "Kısa dinlenme molası ({0}); Instagram'ı yormamak için.": "Short rest ({0}) to go easy on Instagram.",
    " · (durduruldu)": " · (stopped)",
    "Otomatik temizlik: son sohbetler dışındakileri komple sil": "Automatic cleanup: delete everything except the latest chats",
    "Gelen kutundaki tüm sohbetleri tarar, en son yazışılan N sohbeti korur, geri kalanını sırayla gelen kutundan siler. Silinmesini istemediğin bir sohbete ÇİFT TIKLA: yeşil 'Korumalı' olur (tekrar çift tıklarsan kalkar; seçimin hatırlanır).":
        "Scans every chat in your inbox, keeps the N most recent ones and deletes the rest from your inbox one by one. DOUBLE-CLICK a chat you do not want deleted: it turns green 'Protected' (double-click again to undo; your choice is remembered).",
    "Korunacak son sohbet sayısı:": "Number of latest chats to keep:",
    "Sabitlenmiş sohbetleri koru": "Keep pinned chats",
    "Silmeden önce her sohbette kendi mesajlarımı da geri çek (karşı taraftan da kaybolur; ÇOK yavaş)":
        "Also unsend my own messages in each chat before deleting (they vanish for the other person too; VERY slow)",
    "Önce listeden bir sohbet seç (ya da çift tıkla).": "Pick a chat from the list first (or double-click).",
    "Korunacak": "Keep",
    "Silinecek": "Delete",
    "Silinecek sohbet yok.": "There are no chats to delete.",
    "Not: daha eski mesajların da var, yalnızca yüklenenler geri çekilir.": "Note: you have older messages too; only the loaded ones are unsent.",
    "Kayıtlı oturum kullanılamadı: {0}": "Could not use the saved session: {0}",
    "Instagram yavaşlama uyarısı verdi ({0}/{1}). {2} dinlenilecek, sonra daha yavaş devam edilecek.":
        "Instagram issued a slow-down warning ({0}/{1}). Resting for {2}, then continuing more slowly.",
    "Instagram uyarısı: dinleniyor, {0}:{1:02d} sonra devam edilecek...": "Instagram warning: resting, resuming in {0}:{1:02d}...",
    "Kayıtlı oturum geçersiz, yeniden giriş yap.": "The saved session is invalid; log in again.",
    "Doğrulama kodu girilmedi, giriş iptal edildi.": "No verification code entered; login cancelled.",
    "Oturum şifreli kaydedildi.": "Session saved (encrypted).",
    "Oturum kaydedilemedi.": "Could not save the session.",
    "Giriş başarısız: {0}": "Login failed: {0}",
    "Oturumla giriş başarısız: {0}": "Session login failed: {0}",
    "Sohbetler alınamadı: {0}": "Could not fetch chats: {0}",
    "Mesajlar yüklenemedi: {0}": "Could not load messages: {0}",
    "Bağlantı sorunu; {0} sonra yeniden denenecek ({1}/{2}).": "Connection problem; retrying in {0} ({1}/{2}).",
    "Bağlantı bekleniyor: {0} sn sonra yeniden denenecek...": "Waiting for connection: retrying in {0} s...",
    "Instagram uyarıları sürüyor. Uzun mola: {0} ({1}/{2}); sonra daha yavaş, kendiliğinden devam edilecek.":
        "Instagram warnings continue. Long rest: {0} ({1}/{2}); then it resumes by itself, more slowly.",
    "Uzun mola ({0}/{1}): {2} sonra kendiliğinden devam edilecek...": "Long rest ({0}/{1}): resuming by itself in {2}...",
    "{0}/{1} işlendi · sonraki mesaj {2} sn sonra{3} · kalan ≈ {4}": "{0}/{1} done · next message in {2} s{3} · remaining ≈ {4}",
    "Taranan sohbet: {0}": "Chats scanned: {0}",
    "Sohbetler taranamadı: {0}": "Could not scan chats: {0}",
    "Silindi": "Deleted",
    "[{0}/{1}] silindi: {2}": "[{0}/{1}] deleted: {2}",
    "Hata": "Error",
    "[{0}/{1}] silinemedi: {2}": "[{0}/{1}] could not delete: {2}",
    "{0}/{1} işlendi · sonraki sohbet {2} sn sonra{3} · kalan ≈ {4}": "{0}/{1} done · next chat in {2} s{3} · remaining ≈ {4}",
    "2 adımlı doğrulama kodu bekleniyor...": "Waiting for the two-step verification code...",
    "2 adımlı doğrulama": "Two-step verification",
    "Instagram 2 adımlı doğrulama kodunu istiyor.\n\nDoğrulama uygulamandaki 6 haneli kodu (veya SMS / yedek kodu) yaz:":
        "Instagram is asking for the two-step verification code.\n\nEnter the 6-digit code from your authenticator app (or the SMS / backup code):",
    "Instagram bu sohbetten mesaj döndürmedi (yanıt alanları: {0}).": "Instagram returned no messages for this chat (response fields: {0}).",
    "Yükleme hatası: {0}": "Loading error: {0}",
    "Hata: {0}": "Error: {0}",
    "Sohbet silinemedi: {0}": "Could not delete the chat: {0}",
    "Tarama hatası: {0}": "Scan error: {0}",
    "{0}/{1} · {2} siliniyor...": "{0}/{1} · deleting {2}...",
    "{0}: {1} mesaj geri çekilecek.": "{0}: {1} messages will be unsent.",
    "Hata ({0}): {1}": "Error ({0}): {1}",
    "Instagram sınırlama uyardı. Hesabı korumak için DURDURULDU. Birkaç saat bekle.":
        "Instagram issued a rate-limit warning. STOPPED to protect the account. Wait a few hours.",
    "geri çekildi": "unsent",
    "başarısız": "failed",
    " (dinlenme molası)": " (resting)",
    "Instagram sınırlama uyardı. Hesabı korumak için DURDURULDU. Birkaç saat sonra tekrar başlat.":
        "Instagram issued a rate-limit warning. STOPPED to protect the account. Start again in a few hours.",
    "Kod kabul edilmedi, tekrar dene.": "The code was not accepted; try again.",
    "{0}/{1} · {2}: mesaj {3}/{4} işlendi · sonraki {5} sn sonra{6}": "{0}/{1} · {2}: message {3}/{4} done · next in {5} s{6}",
    "Araç": "Tool",
    "İşlenecek": "To process",
    "Kalacak": "Kept",
    "Tamam": "OK",
    "ONAY": "CONFIRM",
    "Tara ve planla": "Scan and plan",
    "Başlat": "Start",
    "Henüz tarama yapılmadı.\nYukarıdaki düğmeyle listeyi oluştur.": "No scan yet.\nBuild the list with the button above.",
    "Arşivlenmiş story temizleyici": "Archived story cleaner",
    "Belirlediğin tarihten ÖNCEKİ arşivlenmiş storyleri kalıcı olarak siler. Arşivi tarar, gün gün listeler; silinmesini istemediğin bir güne ÇİFT TIKLA (yeşil 'Korumalı' olur). Silinen story geri getirilemez.":
        "Permanently deletes archived stories from BEFORE the date you choose. It scans the archive and lists it day by day; DOUBLE-CLICK a day you do not want deleted (it turns green 'Protected'). Deleted stories cannot be restored.",
    "Arşivi tara ve planla": "Scan archive and plan",
    "Eski storyleri sil": "Delete old stories",
    "Engellenen hesapların engelini otomatik kaldır": "Automatically unblock blocked accounts",
    "Engellediğin tüm hesapları listeler ve engellerini tek tek, yavaşça kaldırır. Engelli KALMASINI istediğin kişiye ÇİFT TIKLA: yeşil 'Korumalı' olur ve bu seçim hatırlanır. Engeli kalkan kişi profilini yeniden görebilir ve seni takip etmeyi deneyebilir.":
        "Lists every account you blocked and unblocks them one by one, slowly. DOUBLE-CLICK an account that should STAY blocked: it turns green 'Protected' and the choice is remembered. An unblocked person can see your profile again and try to follow you.",
    "Engeli kalkacak": "To unblock",
    "Engelli kalacak": "Stays blocked",
    "Engeli kalktı": "Unblocked",
    "KALDIR": "REMOVE",
    "Engelleri tara ve planla": "Scan blocks and plan",
    "Engelleri kaldır": "Remove blocks",
    "Fotoğraf": "Photo",
    "Video": "Video",
    "Albüm": "Album",
    "Taranan kayıt": "Entries scanned",
    "Tüm beğenileri otomatik kaldır": "Automatically remove all likes",
    "Beğendiğin tüm gönderi ve reelleri listeler, beğenilerini tek tek, yavaşça kaldırır. Beğenisi KALSIN istediğin bir gönderiye ÇİFT TIKLA (yeşil 'Korumalı' olur). Not: yorum beğenileri bu listede yer almaz.":
        "Lists every post and reel you liked and removes the likes one by one, slowly. DOUBLE-CLICK a post whose like should STAY (it turns green 'Protected'). Note: comment likes are not part of this list.",
    "Taranan beğeni": "Likes scanned",
    "Beğeni kalkacak": "Like to remove",
    "Beğeni kalacak": "Like stays",
    "Beğeni kalktı": "Like removed",
    "Beğenileri tara ve planla": "Scan likes and plan",
    "Beğenileri kaldır": "Remove likes",
    "Kaydedilen gönderi ve reelleri temizle": "Clear saved posts and reels",
    "Hesabında kaydettiğin (yer imi) tüm gönderi ve reelleri listeler ve kayıtlarını tek tek, yavaşça kaldırır. Kaydı KALSIN istediğin bir gönderiye ÇİFT TIKLA (yeşil 'Korumalı' olur). Gönderinin kendisi silinmez; yalnızca senin 'Kaydedilenler' listenden çıkar.":
        "Lists every post and reel you saved (bookmarked) and removes the saves one by one, slowly. DOUBLE-CLICK a post whose save should STAY (it turns green 'Protected'). The post itself is not deleted; it only leaves your 'Saved' list.",
    "Kayıt kalkacak": "Save to remove",
    "Kayıt kalacak": "Save stays",
    "Kayıt kalktı": "Save removed",
    "Kaydedilenleri tara ve planla": "Scan saved items and plan",
    "Kayıtları kaldır": "Remove saves",
    "{0} kayıt işlenecek, {1} kayıt korunacak.": "{0} entries will be processed, {1} entries will be kept.",
    "{0:%d.%m.%Y} tarihinden önceki {1} güne ait yaklaşık {2} arşivlenmiş story KALICI olarak silinecek ({3} gün kalacak). Bu işlem geri alınamaz.":
        "About {2} archived stories from {1} days before {0:%d.%m.%Y} will be PERMANENTLY deleted ({3} days stay). This cannot be undone.",
    "{0} ({1} story)": "{0} ({1} stories)",
    "{0} hesabın engeli kaldırılacak, {1} hesap engelli kalacak. Engellediğin kişiler (taciz eden ya da istemediğin hesaplar dahil) seni yeniden görebilecek.":
        "{0} accounts will be unblocked, {1} accounts stay blocked. The people you blocked (including harassers or unwanted accounts) will be able to see you again.",
    "{0} gönderinin beğenisi kaldırılacak, {1} beğeni kalacak.": "The like will be removed from {0} posts, {1} likes stay.",
    "{0} gönderi/reel 'Kaydedilenler' listenden çıkarılacak, {1} kayıt kalacak. Gönderilerin kendisi silinmez.":
        "{0} posts/reels will leave your 'Saved' list, {1} saves stay. The posts themselves are not deleted.",
    "{0}: tarama başladı.": "{0}: scan started.",
    "{0}: {1} kayıt bulundu.": "{0}: {1} entries found.",
    "{0}\n\nTahmini süre: yaklaşık {1} ({2} hız). İşlem yavaş ve kendiliğinden ilerler; bilgisayar uykuya geçmez, pencereyi açık bırak. Instagram uyarı verirse program kendiliğinden yavaşlar, dinlenir ya da durur.\n\nOnaylamak için  {3}  yaz:":
        "{0}\n\nEstimated time: about {1} ({2} speed). The task is slow and runs by itself; your computer will not go to sleep, keep the window open. If Instagram warns, the app slows down, rests or stops by itself.\n\nType  {3}  to confirm:",
    "{0}: otomatik işlem başladı ({1} hız): {2} kayıt.": "{0}: automatic task started ({1} speed): {2} entries.",
    "Başarılı: {0} · başarısız: {1}": "Succeeded: {0} · failed: {1}",
    "Gün": "Day",
    "Story sayısı": "Stories",
    "Ad": "Name",
    "Engellendiği tarih": "Blocked on",
    "Hesap": "Account",
    "Tür": "Type",
    "Gönderi tarihi": "Post date",
    "Açıklama": "Caption",
    "Önce tara düğmesine bas.": "Press the scan button first.",
    "Taranıyor...": "Scanning...",
    "{0} işlenecek · {1} korunacak/kalacak": "{0} to process · {1} to keep",
    "{0}: onaylanmadı, iptal edildi.": "{0}: not confirmed, cancelled.",
    "{0}: bitti. {1}.": "{0}: finished. {1}.",
    "\n\nİşlem tamamlanmadı. Yeniden tarayıp kaldığın yerden devam edebilirsin.":
        "\n\nThe task did not complete. You can rescan and continue where you left off.",
    "1 ay": "1 month",
    "6 ay": "6 months",
    "1 yıl": "1 year",
    "Taranan gün: {0}": "Days scanned: {0}",
    "Taranan engelli hesap: {0}": "Blocked accounts scanned: {0}",
    "Tarih geçersiz. GG.AA.YYYY biçiminde yaz (örn. 01.03.2025).": "Invalid date. Use the DD.MM.YYYY format (e.g. 01.03.2025).",
    "Reel": "Reel",
    "İşlenecek kayıt yok.": "There are no entries to process.",
})
